name = "Bramble"
uuid = "72287966-2ff3-4442-8755-61ed245be5f7"
version = "1.1.1"
authors = ["Gon√ßalo Pena <goncalo.pena@uc.pt>"]

[deps]
Cubature = "667455a9-e2ce-5579-9412-b964f529a492"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
FunctionWrappers = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
Integrals = "de52edbc-65ea-441a-8357-d3a637375a31"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
MuladdMacro = "46d2c3a1-f734-5fdb-9937-b9b9aeba4221"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[weakdeps]
MakieCore = "20f20a25-4f0e-4fdf-b5d1-57303727442b"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"

[extensions]
BrambleMeshesExt = ["Meshes", "MakieCore"]

[compat]
Cubature = "1.5.1"
FillArrays = "1.13.0"
FunctionWrappers = "1.0"
OrderedCollections = "1.8.0"
UnPack = "1.0.2"
julia = "1.12.1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua", "JET", "LinearAlgebra", "SparseArrays"]

[workspace]
projects = ["test", "docs"]